// <auto-generated />
using System;
using FEAR.Host.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FEAR.Hosted.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("FEAR.Domain.Dto.Authentication.InvestigationRoleAssignment", b =>
                {
                    b.Property<Guid>("InvestigationRoleAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InvestigationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("InvestigationRoleAssignmentId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("InvestigationRoleAssignments", (string)null);
                });

            modelBuilder.Entity("FEAR.Domain.Dto.Authentication.PermissionSet", b =>
                {
                    b.Property<Guid>("PermissionSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PermissionSetId");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("FEAR.Domain.Dto.Authentication.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("FEAR.Domain.Dto.Authentication.SystemAction", b =>
                {
                    b.Property<Guid>("SystemActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SystemActionId");

                    b.ToTable("SystemActions", (string)null);
                });

            modelBuilder.Entity("FEAR.Domain.Dto.Authentication.SystemRoleAssignment", b =>
                {
                    b.Property<Guid>("SystemRoleAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SystemRoleAssignmentId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("SystemRoleAssignments", (string)null);
                });

            modelBuilder.Entity("FEAR.Domain.Dto.Authentication.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FEAR.Domain.Dto.Authentication.UserRefreshToken", b =>
                {
                    b.Property<Guid>("UserRefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp");

                    b.HasKey("UserRefreshTokenId");

                    b.ToTable("UserRefreshTokens", (string)null);
                });

            modelBuilder.Entity("FEAR.Domain.Dto.Authentication.UserSecret", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserSecrets", (string)null);
                });

            modelBuilder.Entity("PermissionSetRole", b =>
                {
                    b.Property<Guid>("PermissionSetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolesRoleId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionSetId", "RolesRoleId");

                    b.HasIndex("RolesRoleId");

                    b.ToTable("PermissionSetRole");
                });

            modelBuilder.Entity("PermissionSetSystemAction", b =>
                {
                    b.Property<Guid>("ApprovedActionsSystemActionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApprovedPermissionSetsPermissionSetId")
                        .HasColumnType("uuid");

                    b.HasKey("ApprovedActionsSystemActionId", "ApprovedPermissionSetsPermissionSetId");

                    b.HasIndex("ApprovedPermissionSetsPermissionSetId");

                    b.ToTable("PermissionSetsApprovedActions", (string)null);
                });

            modelBuilder.Entity("PermissionSetSystemAction1", b =>
                {
                    b.Property<Guid>("DeniedActionsSystemActionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeniedPermissionSetsPermissionSetId")
                        .HasColumnType("uuid");

                    b.HasKey("DeniedActionsSystemActionId", "DeniedPermissionSetsPermissionSetId");

                    b.HasIndex("DeniedPermissionSetsPermissionSetId");

                    b.ToTable("PermissionSetsDeniedActions", (string)null);
                });

            modelBuilder.Entity("FEAR.Domain.Dto.Authentication.InvestigationRoleAssignment", b =>
                {
                    b.HasOne("FEAR.Domain.Dto.Authentication.Role", "Role")
                        .WithMany("InvestigationRoleAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FEAR.Domain.Dto.Authentication.User", "User")
                        .WithMany("InvestigationRoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FEAR.Domain.Dto.Authentication.SystemRoleAssignment", b =>
                {
                    b.HasOne("FEAR.Domain.Dto.Authentication.Role", "Role")
                        .WithMany("SystemRoleAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FEAR.Domain.Dto.Authentication.User", "User")
                        .WithMany("SystemRoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FEAR.Domain.Dto.Authentication.UserSecret", b =>
                {
                    b.HasOne("FEAR.Domain.Dto.Authentication.User", "User")
                        .WithOne("UserSecret")
                        .HasForeignKey("FEAR.Domain.Dto.Authentication.UserSecret", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PermissionSetRole", b =>
                {
                    b.HasOne("FEAR.Domain.Dto.Authentication.PermissionSet", null)
                        .WithMany()
                        .HasForeignKey("PermissionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FEAR.Domain.Dto.Authentication.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionSetSystemAction", b =>
                {
                    b.HasOne("FEAR.Domain.Dto.Authentication.SystemAction", null)
                        .WithMany()
                        .HasForeignKey("ApprovedActionsSystemActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FEAR.Domain.Dto.Authentication.PermissionSet", null)
                        .WithMany()
                        .HasForeignKey("ApprovedPermissionSetsPermissionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionSetSystemAction1", b =>
                {
                    b.HasOne("FEAR.Domain.Dto.Authentication.SystemAction", null)
                        .WithMany()
                        .HasForeignKey("DeniedActionsSystemActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FEAR.Domain.Dto.Authentication.PermissionSet", null)
                        .WithMany()
                        .HasForeignKey("DeniedPermissionSetsPermissionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FEAR.Domain.Dto.Authentication.Role", b =>
                {
                    b.Navigation("InvestigationRoleAssignments");

                    b.Navigation("SystemRoleAssignments");
                });

            modelBuilder.Entity("FEAR.Domain.Dto.Authentication.User", b =>
                {
                    b.Navigation("InvestigationRoleAssignments");

                    b.Navigation("SystemRoleAssignments");

                    b.Navigation("UserSecret")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
