namespace FEAR.Domain.Model.ProtectedEncryptionKey
{
    /// <summary>
    /// Represents the data model for entering encryption keys online when the system requires key input
    /// before unlocking and continuing the loading process. This model supports both manual and automatic
    /// key entry scenarios, including multiple key identifiers and values.
    /// </summary>
    public class EncryptDataModel
    {
        /// <summary>
        /// Gets or sets the array of key identifiers (e.g., key IDs or labels) required for decryption.
        /// </summary>
        public string[] keyIdentifiers { get; set; }

        /// <summary>
        /// Gets or sets the array of key values corresponding to the key identifiers.
        /// </summary>
        public string[] keyValues { get; set; }

        /// <summary>
        /// Gets or sets the name of the key being entered or generated.
        /// This is to synchronize the entry of valid keys by authorized users,
        /// it assumes that authorized users will all use the same key name.
        /// </summary>
        public string keyName { get; set; }

        /// <summary>
        /// Gets or sets the key value as a single string, typically entered via a textarea for convenience.
        /// </summary>
        public string? keyValueTextarea { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the key should be automatically generated by the system.
        /// </summary>
        public bool autoGenerateKey { get; set; }
    }
}
