//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:/Source/Repos/Research/FEAR/FEAR.Core/CFEARParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace FEAR {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CFEARParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ICFEARParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] CFEARParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.enumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumDeclaration([NotNull] CFEARParser.EnumDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.enumConstants"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumConstants([NotNull] CFEARParser.EnumConstantsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.enumConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumConstant([NotNull] CFEARParser.EnumConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldDeclaration([NotNull] CFEARParser.FieldDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.variableDeclarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclarators([NotNull] CFEARParser.VariableDeclaratorsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclarator([NotNull] CFEARParser.VariableDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.variableDeclaratorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaratorId([NotNull] CFEARParser.VariableDeclaratorIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.variableInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableInitializer([NotNull] CFEARParser.VariableInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.arrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayInitializer([NotNull] CFEARParser.ArrayInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] CFEARParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.integerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerLiteral([NotNull] CFEARParser.IntegerLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatLiteral([NotNull] CFEARParser.FloatLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] CFEARParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStatement([NotNull] CFEARParser.BlockStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.localVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalVariableDeclaration([NotNull] CFEARParser.LocalVariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] CFEARParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.diskSearchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiskSearchStatement([NotNull] CFEARParser.DiskSearchStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.networkSearchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNetworkSearchStatement([NotNull] CFEARParser.NetworkSearchStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.acceptsStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAcceptsStatement([NotNull] CFEARParser.AcceptsStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.collectorStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollectorStatement([NotNull] CFEARParser.CollectorStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.collectorDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollectorDefinition([NotNull] CFEARParser.CollectorDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.collectorUse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollectorUse([NotNull] CFEARParser.CollectorUseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.interpreterStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpreterStatement([NotNull] CFEARParser.InterpreterStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.moduleStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleStatement([NotNull] CFEARParser.ModuleStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] CFEARParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.forControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForControl([NotNull] CFEARParser.ForControlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.forInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForInit([NotNull] CFEARParser.ForInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.foreachControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForeachControl([NotNull] CFEARParser.ForeachControlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.parExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParExpression([NotNull] CFEARParser.ParExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionList([NotNull] CFEARParser.ExpressionListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCall([NotNull] CFEARParser.MethodCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] CFEARParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary([NotNull] CFEARParser.PrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.typeType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeType([NotNull] CFEARParser.TypeTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveType([NotNull] CFEARParser.PrimitiveTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.primitiveTypeIdentifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveTypeIdentifiers([NotNull] CFEARParser.PrimitiveTypeIdentifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CFEARParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArguments([NotNull] CFEARParser.ArgumentsContext context);
}
} // namespace FEAR
