//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:/Source/Repos/Research/FEAR/FEAR.Core/GFEARParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace FEAR {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GFEARParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IGFEARParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] GFEARParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.entityUri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntityUri([NotNull] GFEARParser.EntityUriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] GFEARParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.integerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerLiteral([NotNull] GFEARParser.IntegerLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatLiteral([NotNull] GFEARParser.FloatLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.identifiedByEntityClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifiedByEntityClause([NotNull] GFEARParser.IdentifiedByEntityClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.identifiedByPropertyClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifiedByPropertyClause([NotNull] GFEARParser.IdentifiedByPropertyClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.identifiedByClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifiedByClause([NotNull] GFEARParser.IdentifiedByClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.identifiedByClauseBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifiedByClauseBlock([NotNull] GFEARParser.IdentifiedByClauseBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.resultEntityBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResultEntityBlock([NotNull] GFEARParser.ResultEntityBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] GFEARParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStatement([NotNull] GFEARParser.BlockStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] GFEARParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.createPropertyCollectionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreatePropertyCollectionStatement([NotNull] GFEARParser.CreatePropertyCollectionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.createPropertyValueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreatePropertyValueStatement([NotNull] GFEARParser.CreatePropertyValueStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.createPropertyRelationshipStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreatePropertyRelationshipStatement([NotNull] GFEARParser.CreatePropertyRelationshipStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.createPropertyRelationshipUriStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreatePropertyRelationshipUriStatement([NotNull] GFEARParser.CreatePropertyRelationshipUriStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.createPropertyEntityStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreatePropertyEntityStatement([NotNull] GFEARParser.CreatePropertyEntityStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.createPropertyStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreatePropertyStatement([NotNull] GFEARParser.CreatePropertyStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.createCollectionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateCollectionStatement([NotNull] GFEARParser.CreateCollectionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.createEntityStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateEntityStatement([NotNull] GFEARParser.CreateEntityStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.appendEntityStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppendEntityStatement([NotNull] GFEARParser.AppendEntityStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.appendPropertyValueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppendPropertyValueStatement([NotNull] GFEARParser.AppendPropertyValueStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.appendPropertyRelationshipStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppendPropertyRelationshipStatement([NotNull] GFEARParser.AppendPropertyRelationshipStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.acceptsStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAcceptsStatement([NotNull] GFEARParser.AcceptsStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.includeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncludeStatement([NotNull] GFEARParser.IncludeStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.prefixStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefixStatement([NotNull] GFEARParser.PrefixStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.codifierDefinitionBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodifierDefinitionBlock([NotNull] GFEARParser.CodifierDefinitionBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.codifierDefinitionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodifierDefinitionStatement([NotNull] GFEARParser.CodifierDefinitionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.iriFormatClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIriFormatClause([NotNull] GFEARParser.IriFormatClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.ontologyStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOntologyStatement([NotNull] GFEARParser.OntologyStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.ontologyPrefixStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOntologyPrefixStatement([NotNull] GFEARParser.OntologyPrefixStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] GFEARParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.foreachControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForeachControl([NotNull] GFEARParser.ForeachControlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.parExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParExpression([NotNull] GFEARParser.ParExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] GFEARParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GFEARParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary([NotNull] GFEARParser.PrimaryContext context);
}
} // namespace FEAR
