//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from g:/PhD/Source/Research/FEAR/FEAR.Core/IFEARParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace FEAR {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="IFEARParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IIFEARParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="IFEARParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] IFEARParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IFEARParser.interpreter_source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpreter_source([NotNull] IFEARParser.Interpreter_sourceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IFEARParser.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldDeclaration([NotNull] IFEARParser.FieldDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IFEARParser.variableDeclarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclarators([NotNull] IFEARParser.VariableDeclaratorsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IFEARParser.variableDeclaratorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaratorId([NotNull] IFEARParser.VariableDeclaratorIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IFEARParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] IFEARParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IFEARParser.codify_line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodify_line([NotNull] IFEARParser.Codify_lineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IFEARParser.assignment_line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_line([NotNull] IFEARParser.Assignment_lineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IFEARParser.assignment_action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_action([NotNull] IFEARParser.Assignment_actionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IFEARParser.assignment_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_function([NotNull] IFEARParser.Assignment_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IFEARParser.uri_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUri_identifier([NotNull] IFEARParser.Uri_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IFEARParser.interpreter_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpreter_definition([NotNull] IFEARParser.Interpreter_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IFEARParser.skipStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSkipStatement([NotNull] IFEARParser.SkipStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IFEARParser.interpreterStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpreterStatement([NotNull] IFEARParser.InterpreterStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IFEARParser.type_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_specifier([NotNull] IFEARParser.Type_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IFEARParser.type_conversion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_conversion([NotNull] IFEARParser.Type_conversionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IFEARParser.interpreter_use"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpreter_use([NotNull] IFEARParser.Interpreter_useContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IFEARParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringLiteral([NotNull] IFEARParser.StringLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IFEARParser.variable_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_reference([NotNull] IFEARParser.Variable_referenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IFEARParser.numericLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericLiteral([NotNull] IFEARParser.NumericLiteralContext context);
}
} // namespace FEAR
