//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from g:/PhD/Source/Research/FEAR/FEAR.Core/IFEARParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace FEAR {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class IFEARParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		Break=1, Else=2, Var=3, Return=4, Void=5, Continue=6, For=7, Foreach=8, 
		While=9, With=10, Create=11, Collection=12, Append=13, Function_=14, If=15, 
		In=16, To=17, As=18, Of=19, New=20, EndL=21, EndB=22, Iri=23, Segment=24, 
		Define=25, Internal=26, Interpreter_=27, Collector=28, Codifier=29, Module=30, 
		Codify=31, Ontology=32, Entity=33, Property=34, Include=35, Identified=36, 
		By=37, Prefix_=38, Accepts=39, Search=40, Result=41, Required=42, Optional=43, 
		InterpreterSkip=44, OpenBracket=45, CloseBracket=46, OpenParen=47, CloseParen=48, 
		OpenBrace=49, CloseBrace=50, SemiColon=51, Comma=52, Assign=53, QuestionMark=54, 
		Colon=55, Dot=56, PlusPlus=57, MinusMinus=58, Plus=59, Minus=60, BitNot=61, 
		Not=62, Multiply=63, Divide=64, Modulus=65, LessThan=66, MoreThan=67, 
		LessThanEquals=68, GreaterThanEquals=69, Equals_=70, NotEquals=71, RightShiftArithmetic=72, 
		LeftShiftArithmetic=73, BitAnd=74, BitXOr=75, BitOr=76, And=77, Or=78, 
		Arrow=79, ColonColon=80, NULL_LITERAL=81, DECIMAL_LITERAL=82, HEX_LITERAL=83, 
		OCT_LITERAL=84, BINARY_LITERAL=85, FLOAT_LITERAL=86, HEX_FLOAT_LITERAL=87, 
		BOOL_LITERAL=88, CHAR_LITERAL=89, STRING_LITERAL=90, Whitespace=91, MultiLineComment=92, 
		SingleLineComment=93, Newline=94, UnexpectedCharacter=95, IDENTIFIER=96, 
		Object=97, TypeConversion=98;
	public const int
		RULE_program = 0, RULE_interpreter_source = 1, RULE_fieldDeclaration = 2, 
		RULE_variableDeclarators = 3, RULE_variableDeclaratorId = 4, RULE_statement = 5, 
		RULE_codify_line = 6, RULE_assignment_line = 7, RULE_assignment_action = 8, 
		RULE_assignment_function = 9, RULE_uri_identifier = 10, RULE_interpreter_definition = 11, 
		RULE_skipStatement = 12, RULE_interpreterStatement = 13, RULE_type_specifier = 14, 
		RULE_type_conversion = 15, RULE_interpreter_use = 16, RULE_stringLiteral = 17, 
		RULE_variable_reference = 18, RULE_numericLiteral = 19;
	public static readonly string[] ruleNames = {
		"program", "interpreter_source", "fieldDeclaration", "variableDeclarators", 
		"variableDeclaratorId", "statement", "codify_line", "assignment_line", 
		"assignment_action", "assignment_function", "uri_identifier", "interpreter_definition", 
		"skipStatement", "interpreterStatement", "type_specifier", "type_conversion", 
		"interpreter_use", "stringLiteral", "variable_reference", "numericLiteral"
	};

	private static readonly string[] _LiteralNames = {
		null, "'break'", "'else'", "'var'", "'return'", "'void'", "'continue'", 
		"'for'", "'foreach'", "'while'", "'with'", "'create'", "'collection'", 
		"'append'", "'function'", "'if'", "'in'", "'to'", "'as'", "'of'", "'new'", 
		"'L'", "'B'", "'iri'", "'segment'", "'define'", "'internal'", "'interpreter'", 
		"'collector'", "'codifier'", "'module'", "'codify'", "'ontology'", "'entity'", 
		"'property'", "'include'", "'identified'", "'by'", "'prefix'", "'accepts'", 
		"'search'", "'result'", "'required'", "'optional'", "'S'", "'['", "']'", 
		"'('", "')'", "'{'", "'}'", "';'", "','", "'='", "'?'", "':'", "'.'", 
		"'++'", "'--'", "'+'", "'-'", "'~'", "'!'", "'*'", "'/'", "'%'", "'<'", 
		"'>'", "'<='", "'>='", "'=='", "'!='", "'>>'", "'<<'", "'&'", "'^'", "'|'", 
		"'&&'", "'||'", "'=>'", "'::'", "'null'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "Break", "Else", "Var", "Return", "Void", "Continue", "For", "Foreach", 
		"While", "With", "Create", "Collection", "Append", "Function_", "If", 
		"In", "To", "As", "Of", "New", "EndL", "EndB", "Iri", "Segment", "Define", 
		"Internal", "Interpreter_", "Collector", "Codifier", "Module", "Codify", 
		"Ontology", "Entity", "Property", "Include", "Identified", "By", "Prefix_", 
		"Accepts", "Search", "Result", "Required", "Optional", "InterpreterSkip", 
		"OpenBracket", "CloseBracket", "OpenParen", "CloseParen", "OpenBrace", 
		"CloseBrace", "SemiColon", "Comma", "Assign", "QuestionMark", "Colon", 
		"Dot", "PlusPlus", "MinusMinus", "Plus", "Minus", "BitNot", "Not", "Multiply", 
		"Divide", "Modulus", "LessThan", "MoreThan", "LessThanEquals", "GreaterThanEquals", 
		"Equals_", "NotEquals", "RightShiftArithmetic", "LeftShiftArithmetic", 
		"BitAnd", "BitXOr", "BitOr", "And", "Or", "Arrow", "ColonColon", "NULL_LITERAL", 
		"DECIMAL_LITERAL", "HEX_LITERAL", "OCT_LITERAL", "BINARY_LITERAL", "FLOAT_LITERAL", 
		"HEX_FLOAT_LITERAL", "BOOL_LITERAL", "CHAR_LITERAL", "STRING_LITERAL", 
		"Whitespace", "MultiLineComment", "SingleLineComment", "Newline", "UnexpectedCharacter", 
		"IDENTIFIER", "Object", "TypeConversion"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "IFEARParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static IFEARParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public IFEARParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public IFEARParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Interpreter_definitionContext interpreter_definition() {
			return GetRuleContext<Interpreter_definitionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Interpreter_sourceContext interpreter_source() {
			return GetRuleContext<Interpreter_sourceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(IFEARParser.Eof, 0); }
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIFEARParserVisitor<TResult> typedVisitor = visitor as IIFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 40;
			interpreter_definition();
			State = 41;
			interpreter_source();
			State = 42;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Interpreter_sourceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public Interpreter_sourceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_interpreter_source; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIFEARParserVisitor<TResult> typedVisitor = visitor as IIFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInterpreter_source(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Interpreter_sourceContext interpreter_source() {
		Interpreter_sourceContext _localctx = new Interpreter_sourceContext(Context, State);
		EnterRule(_localctx, 2, RULE_interpreter_source);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 47;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 17594534854656L) != 0) || _la==IDENTIFIER) {
				{
				{
				State = 44;
				statement();
				}
				}
				State = 49;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Internal() { return GetToken(IFEARParser.Internal, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public VariableDeclaratorsContext variableDeclarators() {
			return GetRuleContext<VariableDeclaratorsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(IFEARParser.SemiColon, 0); }
		public FieldDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fieldDeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIFEARParserVisitor<TResult> typedVisitor = visitor as IIFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFieldDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FieldDeclarationContext fieldDeclaration() {
		FieldDeclarationContext _localctx = new FieldDeclarationContext(Context, State);
		EnterRule(_localctx, 4, RULE_fieldDeclaration);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 50;
			Match(Internal);
			State = 51;
			variableDeclarators();
			State = 52;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableDeclaratorsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public VariableDeclaratorIdContext[] variableDeclaratorId() {
			return GetRuleContexts<VariableDeclaratorIdContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public VariableDeclaratorIdContext variableDeclaratorId(int i) {
			return GetRuleContext<VariableDeclaratorIdContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comma() { return GetTokens(IFEARParser.Comma); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma(int i) {
			return GetToken(IFEARParser.Comma, i);
		}
		public VariableDeclaratorsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableDeclarators; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIFEARParserVisitor<TResult> typedVisitor = visitor as IIFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableDeclarators(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableDeclaratorsContext variableDeclarators() {
		VariableDeclaratorsContext _localctx = new VariableDeclaratorsContext(Context, State);
		EnterRule(_localctx, 6, RULE_variableDeclarators);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 54;
			variableDeclaratorId();
			State = 59;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Comma) {
				{
				{
				State = 55;
				Match(Comma);
				State = 56;
				variableDeclaratorId();
				}
				}
				State = 61;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableDeclaratorIdContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(IFEARParser.IDENTIFIER, 0); }
		public VariableDeclaratorIdContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableDeclaratorId; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIFEARParserVisitor<TResult> typedVisitor = visitor as IIFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableDeclaratorId(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableDeclaratorIdContext variableDeclaratorId() {
		VariableDeclaratorIdContext _localctx = new VariableDeclaratorIdContext(Context, State);
		EnterRule(_localctx, 8, RULE_variableDeclaratorId);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 62;
			Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Interpreter_useContext interpreter_use() {
			return GetRuleContext<Interpreter_useContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Codify_lineContext codify_line() {
			return GetRuleContext<Codify_lineContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FieldDeclarationContext fieldDeclaration() {
			return GetRuleContext<FieldDeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public InterpreterStatementContext interpreterStatement() {
			return GetRuleContext<InterpreterStatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SkipStatementContext skipStatement() {
			return GetRuleContext<SkipStatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Assignment_lineContext assignment_line() {
			return GetRuleContext<Assignment_lineContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIFEARParserVisitor<TResult> typedVisitor = visitor as IIFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 10, RULE_statement);
		try {
			State = 70;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 64;
				interpreter_use();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 65;
				codify_line();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 66;
				fieldDeclaration();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 67;
				interpreterStatement();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 68;
				skipStatement();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 69;
				assignment_line();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Codify_lineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Codify() { return GetToken(IFEARParser.Codify, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Variable_referenceContext variable_reference() {
			return GetRuleContext<Variable_referenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode As() { return GetToken(IFEARParser.As, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(IFEARParser.SemiColon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Object() { return GetToken(IFEARParser.Object, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Property() { return GetToken(IFEARParser.Property, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Uri_identifierContext[] uri_identifier() {
			return GetRuleContexts<Uri_identifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Uri_identifierContext uri_identifier(int i) {
			return GetRuleContext<Uri_identifierContext>(i);
		}
		public Codify_lineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_codify_line; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIFEARParserVisitor<TResult> typedVisitor = visitor as IIFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCodify_line(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Codify_lineContext codify_line() {
		Codify_lineContext _localctx = new Codify_lineContext(Context, State);
		EnterRule(_localctx, 12, RULE_codify_line);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 72;
			Match(Codify);
			State = 73;
			_la = TokenStream.LA(1);
			if ( !(_la==Property || _la==Object) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 74;
			variable_reference();
			State = 75;
			Match(As);
			State = 77;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 76;
				uri_identifier();
				}
				}
				State = 79;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==Colon );
			State = 81;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Assignment_lineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Variable_referenceContext variable_reference() {
			return GetRuleContext<Variable_referenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Assign() { return GetToken(IFEARParser.Assign, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Assignment_actionContext assignment_action() {
			return GetRuleContext<Assignment_actionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(IFEARParser.SemiColon, 0); }
		public Assignment_lineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment_line; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIFEARParserVisitor<TResult> typedVisitor = visitor as IIFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignment_line(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Assignment_lineContext assignment_line() {
		Assignment_lineContext _localctx = new Assignment_lineContext(Context, State);
		EnterRule(_localctx, 14, RULE_assignment_line);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 83;
			variable_reference();
			State = 84;
			Match(Assign);
			State = 85;
			assignment_action();
			State = 86;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Assignment_actionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Variable_referenceContext variable_reference() {
			return GetRuleContext<Variable_referenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumericLiteralContext numericLiteral() {
			return GetRuleContext<NumericLiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StringLiteralContext stringLiteral() {
			return GetRuleContext<StringLiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Assignment_functionContext assignment_function() {
			return GetRuleContext<Assignment_functionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Assignment_actionContext assignment_action() {
			return GetRuleContext<Assignment_actionContext>(0);
		}
		public Assignment_actionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment_action; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIFEARParserVisitor<TResult> typedVisitor = visitor as IIFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignment_action(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Assignment_actionContext assignment_action() {
		Assignment_actionContext _localctx = new Assignment_actionContext(Context, State);
		EnterRule(_localctx, 16, RULE_assignment_action);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 91;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case IDENTIFIER:
				{
				State = 88;
				variable_reference();
				}
				break;
			case Minus:
			case DECIMAL_LITERAL:
				{
				State = 89;
				numericLiteral();
				}
				break;
			case STRING_LITERAL:
				{
				State = 90;
				stringLiteral();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 96;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Plus || _la==Minus) {
				{
				State = 93;
				assignment_function();
				State = 94;
				assignment_action();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Assignment_functionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Plus() { return GetToken(IFEARParser.Plus, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Minus() { return GetToken(IFEARParser.Minus, 0); }
		public Assignment_functionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment_function; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIFEARParserVisitor<TResult> typedVisitor = visitor as IIFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignment_function(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Assignment_functionContext assignment_function() {
		Assignment_functionContext _localctx = new Assignment_functionContext(Context, State);
		EnterRule(_localctx, 18, RULE_assignment_function);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 98;
			_la = TokenStream.LA(1);
			if ( !(_la==Plus || _la==Minus) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Uri_identifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Colon() { return GetToken(IFEARParser.Colon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(IFEARParser.IDENTIFIER, 0); }
		public Uri_identifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_uri_identifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIFEARParserVisitor<TResult> typedVisitor = visitor as IIFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUri_identifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Uri_identifierContext uri_identifier() {
		Uri_identifierContext _localctx = new Uri_identifierContext(Context, State);
		EnterRule(_localctx, 20, RULE_uri_identifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 100;
			Match(Colon);
			State = 101;
			Match(IDENTIFIER);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Interpreter_definitionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Define() { return GetToken(IFEARParser.Define, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Interpreter_() { return GetToken(IFEARParser.Interpreter_, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OpenParen() { return GetToken(IFEARParser.OpenParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StringLiteralContext[] stringLiteral() {
			return GetRuleContexts<StringLiteralContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StringLiteralContext stringLiteral(int i) {
			return GetRuleContext<StringLiteralContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comma() { return GetTokens(IFEARParser.Comma); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma(int i) {
			return GetToken(IFEARParser.Comma, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CloseParen() { return GetToken(IFEARParser.CloseParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(IFEARParser.SemiColon, 0); }
		public Interpreter_definitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_interpreter_definition; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIFEARParserVisitor<TResult> typedVisitor = visitor as IIFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInterpreter_definition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Interpreter_definitionContext interpreter_definition() {
		Interpreter_definitionContext _localctx = new Interpreter_definitionContext(Context, State);
		EnterRule(_localctx, 22, RULE_interpreter_definition);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 103;
			Match(Define);
			State = 104;
			Match(Interpreter_);
			State = 105;
			Match(OpenParen);
			State = 106;
			stringLiteral();
			State = 107;
			Match(Comma);
			State = 108;
			stringLiteral();
			State = 109;
			Match(Comma);
			State = 110;
			stringLiteral();
			State = 111;
			Match(CloseParen);
			State = 112;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SkipStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode InterpreterSkip() { return GetToken(IFEARParser.InterpreterSkip, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Colon() { return GetToken(IFEARParser.Colon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NumericLiteralContext numericLiteral() {
			return GetRuleContext<NumericLiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(IFEARParser.SemiColon, 0); }
		public SkipStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_skipStatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIFEARParserVisitor<TResult> typedVisitor = visitor as IIFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSkipStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SkipStatementContext skipStatement() {
		SkipStatementContext _localctx = new SkipStatementContext(Context, State);
		EnterRule(_localctx, 24, RULE_skipStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 114;
			Match(InterpreterSkip);
			State = 115;
			Match(Colon);
			State = 116;
			numericLiteral();
			State = 117;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InterpreterStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Variable_referenceContext variable_reference() {
			return GetRuleContext<Variable_referenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Assign() { return GetToken(IFEARParser.Assign, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Colon() { return GetTokens(IFEARParser.Colon); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Colon(int i) {
			return GetToken(IFEARParser.Colon, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumericLiteralContext[] numericLiteral() {
			return GetRuleContexts<NumericLiteralContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumericLiteralContext numericLiteral(int i) {
			return GetRuleContext<NumericLiteralContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Type_specifierContext type_specifier() {
			return GetRuleContext<Type_specifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(IFEARParser.SemiColon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndL() { return GetToken(IFEARParser.EndL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndB() { return GetToken(IFEARParser.EndB, 0); }
		public InterpreterStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_interpreterStatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIFEARParserVisitor<TResult> typedVisitor = visitor as IIFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInterpreterStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InterpreterStatementContext interpreterStatement() {
		InterpreterStatementContext _localctx = new InterpreterStatementContext(Context, State);
		EnterRule(_localctx, 26, RULE_interpreterStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 119;
			variable_reference();
			State = 120;
			Match(Assign);
			State = 122;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Minus || _la==DECIMAL_LITERAL) {
				{
				State = 121;
				numericLiteral();
				}
			}

			State = 124;
			Match(Colon);
			State = 125;
			numericLiteral();
			State = 126;
			Match(Colon);
			State = 127;
			type_specifier();
			State = 128;
			Match(Colon);
			State = 130;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==EndL || _la==EndB) {
				{
				State = 129;
				_la = TokenStream.LA(1);
				if ( !(_la==EndL || _la==EndB) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
			}

			State = 132;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_specifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Type_conversionContext type_conversion() {
			return GetRuleContext<Type_conversionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(IFEARParser.IDENTIFIER, 0); }
		public Type_specifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_specifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIFEARParserVisitor<TResult> typedVisitor = visitor as IIFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitType_specifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Type_specifierContext type_specifier() {
		Type_specifierContext _localctx = new Type_specifierContext(Context, State);
		EnterRule(_localctx, 28, RULE_type_specifier);
		try {
			State = 136;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 134;
				type_conversion();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 135;
				Match(IDENTIFIER);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_conversionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENTIFIER() { return GetTokens(IFEARParser.IDENTIFIER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER(int i) {
			return GetToken(IFEARParser.IDENTIFIER, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TypeConversion() { return GetToken(IFEARParser.TypeConversion, 0); }
		public Type_conversionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_conversion; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIFEARParserVisitor<TResult> typedVisitor = visitor as IIFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitType_conversion(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Type_conversionContext type_conversion() {
		Type_conversionContext _localctx = new Type_conversionContext(Context, State);
		EnterRule(_localctx, 30, RULE_type_conversion);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 138;
			Match(IDENTIFIER);
			State = 139;
			Match(TypeConversion);
			State = 140;
			Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Interpreter_useContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Interpreter_() { return GetTokens(IFEARParser.Interpreter_); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Interpreter_(int i) {
			return GetToken(IFEARParser.Interpreter_, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Variable_referenceContext variable_reference() {
			return GetRuleContext<Variable_referenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Assign() { return GetToken(IFEARParser.Assign, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OpenParen() { return GetToken(IFEARParser.OpenParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StringLiteralContext stringLiteral() {
			return GetRuleContext<StringLiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CloseParen() { return GetToken(IFEARParser.CloseParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(IFEARParser.SemiColon, 0); }
		public Interpreter_useContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_interpreter_use; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIFEARParserVisitor<TResult> typedVisitor = visitor as IIFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInterpreter_use(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Interpreter_useContext interpreter_use() {
		Interpreter_useContext _localctx = new Interpreter_useContext(Context, State);
		EnterRule(_localctx, 32, RULE_interpreter_use);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 142;
			Match(Interpreter_);
			State = 143;
			variable_reference();
			State = 144;
			Match(Assign);
			State = 145;
			Match(Interpreter_);
			State = 146;
			Match(OpenParen);
			State = 147;
			stringLiteral();
			State = 148;
			Match(CloseParen);
			State = 149;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringLiteralContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL() { return GetToken(IFEARParser.STRING_LITERAL, 0); }
		public StringLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stringLiteral; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIFEARParserVisitor<TResult> typedVisitor = visitor as IIFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStringLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StringLiteralContext stringLiteral() {
		StringLiteralContext _localctx = new StringLiteralContext(Context, State);
		EnterRule(_localctx, 34, RULE_stringLiteral);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 151;
			Match(STRING_LITERAL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Variable_referenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(IFEARParser.IDENTIFIER, 0); }
		public Variable_referenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variable_reference; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIFEARParserVisitor<TResult> typedVisitor = visitor as IIFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariable_reference(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Variable_referenceContext variable_reference() {
		Variable_referenceContext _localctx = new Variable_referenceContext(Context, State);
		EnterRule(_localctx, 36, RULE_variable_reference);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 153;
			Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumericLiteralContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DECIMAL_LITERAL() { return GetToken(IFEARParser.DECIMAL_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Minus() { return GetToken(IFEARParser.Minus, 0); }
		public NumericLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numericLiteral; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIFEARParserVisitor<TResult> typedVisitor = visitor as IIFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumericLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumericLiteralContext numericLiteral() {
		NumericLiteralContext _localctx = new NumericLiteralContext(Context, State);
		EnterRule(_localctx, 38, RULE_numericLiteral);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 156;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Minus) {
				{
				State = 155;
				Match(Minus);
				}
			}

			State = 158;
			Match(DECIMAL_LITERAL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,98,161,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,1,0,1,0,1,0,1,0,1,1,
		5,1,46,8,1,10,1,12,1,49,9,1,1,2,1,2,1,2,1,2,1,3,1,3,1,3,5,3,58,8,3,10,
		3,12,3,61,9,3,1,4,1,4,1,5,1,5,1,5,1,5,1,5,1,5,3,5,71,8,5,1,6,1,6,1,6,1,
		6,1,6,4,6,78,8,6,11,6,12,6,79,1,6,1,6,1,7,1,7,1,7,1,7,1,7,1,8,1,8,1,8,
		3,8,92,8,8,1,8,1,8,1,8,3,8,97,8,8,1,9,1,9,1,10,1,10,1,10,1,11,1,11,1,11,
		1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,12,1,12,1,12,1,12,1,12,1,13,
		1,13,1,13,3,13,123,8,13,1,13,1,13,1,13,1,13,1,13,1,13,3,13,131,8,13,1,
		13,1,13,1,14,1,14,3,14,137,8,14,1,15,1,15,1,15,1,15,1,16,1,16,1,16,1,16,
		1,16,1,16,1,16,1,16,1,16,1,17,1,17,1,18,1,18,1,19,3,19,157,8,19,1,19,1,
		19,1,19,0,0,20,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,
		0,3,2,0,34,34,97,97,1,0,59,60,1,0,21,22,155,0,40,1,0,0,0,2,47,1,0,0,0,
		4,50,1,0,0,0,6,54,1,0,0,0,8,62,1,0,0,0,10,70,1,0,0,0,12,72,1,0,0,0,14,
		83,1,0,0,0,16,91,1,0,0,0,18,98,1,0,0,0,20,100,1,0,0,0,22,103,1,0,0,0,24,
		114,1,0,0,0,26,119,1,0,0,0,28,136,1,0,0,0,30,138,1,0,0,0,32,142,1,0,0,
		0,34,151,1,0,0,0,36,153,1,0,0,0,38,156,1,0,0,0,40,41,3,22,11,0,41,42,3,
		2,1,0,42,43,5,0,0,1,43,1,1,0,0,0,44,46,3,10,5,0,45,44,1,0,0,0,46,49,1,
		0,0,0,47,45,1,0,0,0,47,48,1,0,0,0,48,3,1,0,0,0,49,47,1,0,0,0,50,51,5,26,
		0,0,51,52,3,6,3,0,52,53,5,51,0,0,53,5,1,0,0,0,54,59,3,8,4,0,55,56,5,52,
		0,0,56,58,3,8,4,0,57,55,1,0,0,0,58,61,1,0,0,0,59,57,1,0,0,0,59,60,1,0,
		0,0,60,7,1,0,0,0,61,59,1,0,0,0,62,63,5,96,0,0,63,9,1,0,0,0,64,71,3,32,
		16,0,65,71,3,12,6,0,66,71,3,4,2,0,67,71,3,26,13,0,68,71,3,24,12,0,69,71,
		3,14,7,0,70,64,1,0,0,0,70,65,1,0,0,0,70,66,1,0,0,0,70,67,1,0,0,0,70,68,
		1,0,0,0,70,69,1,0,0,0,71,11,1,0,0,0,72,73,5,31,0,0,73,74,7,0,0,0,74,75,
		3,36,18,0,75,77,5,18,0,0,76,78,3,20,10,0,77,76,1,0,0,0,78,79,1,0,0,0,79,
		77,1,0,0,0,79,80,1,0,0,0,80,81,1,0,0,0,81,82,5,51,0,0,82,13,1,0,0,0,83,
		84,3,36,18,0,84,85,5,53,0,0,85,86,3,16,8,0,86,87,5,51,0,0,87,15,1,0,0,
		0,88,92,3,36,18,0,89,92,3,38,19,0,90,92,3,34,17,0,91,88,1,0,0,0,91,89,
		1,0,0,0,91,90,1,0,0,0,92,96,1,0,0,0,93,94,3,18,9,0,94,95,3,16,8,0,95,97,
		1,0,0,0,96,93,1,0,0,0,96,97,1,0,0,0,97,17,1,0,0,0,98,99,7,1,0,0,99,19,
		1,0,0,0,100,101,5,55,0,0,101,102,5,96,0,0,102,21,1,0,0,0,103,104,5,25,
		0,0,104,105,5,27,0,0,105,106,5,47,0,0,106,107,3,34,17,0,107,108,5,52,0,
		0,108,109,3,34,17,0,109,110,5,52,0,0,110,111,3,34,17,0,111,112,5,48,0,
		0,112,113,5,51,0,0,113,23,1,0,0,0,114,115,5,44,0,0,115,116,5,55,0,0,116,
		117,3,38,19,0,117,118,5,51,0,0,118,25,1,0,0,0,119,120,3,36,18,0,120,122,
		5,53,0,0,121,123,3,38,19,0,122,121,1,0,0,0,122,123,1,0,0,0,123,124,1,0,
		0,0,124,125,5,55,0,0,125,126,3,38,19,0,126,127,5,55,0,0,127,128,3,28,14,
		0,128,130,5,55,0,0,129,131,7,2,0,0,130,129,1,0,0,0,130,131,1,0,0,0,131,
		132,1,0,0,0,132,133,5,51,0,0,133,27,1,0,0,0,134,137,3,30,15,0,135,137,
		5,96,0,0,136,134,1,0,0,0,136,135,1,0,0,0,137,29,1,0,0,0,138,139,5,96,0,
		0,139,140,5,98,0,0,140,141,5,96,0,0,141,31,1,0,0,0,142,143,5,27,0,0,143,
		144,3,36,18,0,144,145,5,53,0,0,145,146,5,27,0,0,146,147,5,47,0,0,147,148,
		3,34,17,0,148,149,5,48,0,0,149,150,5,51,0,0,150,33,1,0,0,0,151,152,5,90,
		0,0,152,35,1,0,0,0,153,154,5,96,0,0,154,37,1,0,0,0,155,157,5,60,0,0,156,
		155,1,0,0,0,156,157,1,0,0,0,157,158,1,0,0,0,158,159,5,82,0,0,159,39,1,
		0,0,0,10,47,59,70,79,91,96,122,130,136,156
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace FEAR
