//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:/Source/Repos/Research/FEAR/FEAR.Lang/RFEARParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace FEAR {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="RFEARParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IRFEARParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] RFEARParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.entityUri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntityUri([NotNull] RFEARParser.EntityUriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.ruleBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuleBlock([NotNull] RFEARParser.RuleBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.swrlRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwrlRule([NotNull] RFEARParser.SwrlRuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.swrlAntecedent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwrlAntecedent([NotNull] RFEARParser.SwrlAntecedentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.swrlConsequent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwrlConsequent([NotNull] RFEARParser.SwrlConsequentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom([NotNull] RFEARParser.AtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.classAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassAtom([NotNull] RFEARParser.ClassAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.propertyAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyAtom([NotNull] RFEARParser.PropertyAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.builtinAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBuiltinAtom([NotNull] RFEARParser.BuiltinAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] RFEARParser.ArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] RFEARParser.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] RFEARParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.iri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIri([NotNull] RFEARParser.IriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.swrlbIri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwrlbIri([NotNull] RFEARParser.SwrlbIriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.swrlbOrIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwrlbOrIdentifier([NotNull] RFEARParser.SwrlbOrIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.dependsOnClauseBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDependsOnClauseBlock([NotNull] RFEARParser.DependsOnClauseBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.dependsOnClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDependsOnClause([NotNull] RFEARParser.DependsOnClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.includeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncludeStatement([NotNull] RFEARParser.IncludeStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.prefixStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefixStatement([NotNull] RFEARParser.PrefixStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.rulesetDefinitionBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRulesetDefinitionBlock([NotNull] RFEARParser.RulesetDefinitionBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.rulesetDefinitionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRulesetDefinitionStatement([NotNull] RFEARParser.RulesetDefinitionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.ontologyStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOntologyStatement([NotNull] RFEARParser.OntologyStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RFEARParser.ontologyPrefixStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOntologyPrefixStatement([NotNull] RFEARParser.OntologyPrefixStatementContext context);
}
} // namespace FEAR
