//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:/Source/Repos/Research/FEAR/FEAR.Lang/RFEARParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace FEAR {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class RFEARParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		Swrlb=1, Segment=2, Define=3, Ruleset=4, Derived=5, Observed=6, Ontology=7, 
		Include=8, Prefix_=9, Depends_on=10, With=11, OpenParen=12, CloseParen=13, 
		OpenBrace=14, CloseBrace=15, SemiColon=16, Comma=17, Colon=18, Conjunct=19, 
		Indirection=20, LeftAngle=21, RightAngle=22, Whitespace=23, MultiLineComment=24, 
		SingleLineComment=25, Newline=26, IRI=27, VAR=28, STRING_LITERAL=29, NUMBER_LITERAL=30, 
		IDENTIFIER=31;
	public const int
		RULE_program = 0, RULE_entityUri = 1, RULE_ruleBlock = 2, RULE_swrlRule = 3, 
		RULE_swrlAntecedent = 4, RULE_swrlConsequent = 5, RULE_atom = 6, RULE_classAtom = 7, 
		RULE_propertyAtom = 8, RULE_builtinAtom = 9, RULE_argument = 10, RULE_variable = 11, 
		RULE_literal = 12, RULE_iri = 13, RULE_swrlbIri = 14, RULE_swrlbOrIdentifier = 15, 
		RULE_dependsOnClauseBlock = 16, RULE_dependsOnClause = 17, RULE_includeStatement = 18, 
		RULE_prefixStatement = 19, RULE_rulesetDefinitionBlock = 20, RULE_rulesetDefinitionStatement = 21, 
		RULE_ontologyStatement = 22, RULE_ontologyPrefixStatement = 23;
	public static readonly string[] ruleNames = {
		"program", "entityUri", "ruleBlock", "swrlRule", "swrlAntecedent", "swrlConsequent", 
		"atom", "classAtom", "propertyAtom", "builtinAtom", "argument", "variable", 
		"literal", "iri", "swrlbIri", "swrlbOrIdentifier", "dependsOnClauseBlock", 
		"dependsOnClause", "includeStatement", "prefixStatement", "rulesetDefinitionBlock", 
		"rulesetDefinitionStatement", "ontologyStatement", "ontologyPrefixStatement"
	};

	private static readonly string[] _LiteralNames = {
		null, "'swrlb'", "'segment'", "'define'", "'ruleset'", "'derived'", "'observed'", 
		"'ontology'", "'include'", "'prefix'", "'depends on'", "'with'", "'('", 
		"')'", "'{'", "'}'", "';'", "','", "':'", "'^'", "'->'", "'<'", "'>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "Swrlb", "Segment", "Define", "Ruleset", "Derived", "Observed", 
		"Ontology", "Include", "Prefix_", "Depends_on", "With", "OpenParen", "CloseParen", 
		"OpenBrace", "CloseBrace", "SemiColon", "Comma", "Colon", "Conjunct", 
		"Indirection", "LeftAngle", "RightAngle", "Whitespace", "MultiLineComment", 
		"SingleLineComment", "Newline", "IRI", "VAR", "STRING_LITERAL", "NUMBER_LITERAL", 
		"IDENTIFIER"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "RFEARParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static RFEARParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public RFEARParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public RFEARParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RulesetDefinitionBlockContext rulesetDefinitionBlock() {
			return GetRuleContext<RulesetDefinitionBlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(RFEARParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public RuleBlockContext[] ruleBlock() {
			return GetRuleContexts<RuleBlockContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RuleBlockContext ruleBlock(int i) {
			return GetRuleContext<RuleBlockContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 48;
			rulesetDefinitionBlock();
			State = 52;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Derived || _la==Observed) {
				{
				{
				State = 49;
				ruleBlock();
				}
				}
				State = 54;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 55;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntityUriContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENTIFIER() { return GetTokens(RFEARParser.IDENTIFIER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER(int i) {
			return GetToken(RFEARParser.IDENTIFIER, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Colon() { return GetToken(RFEARParser.Colon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IRI() { return GetToken(RFEARParser.IRI, 0); }
		public EntityUriContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entityUri; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEntityUri(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EntityUriContext entityUri() {
		EntityUriContext _localctx = new EntityUriContext(Context, State);
		EnterRule(_localctx, 2, RULE_entityUri);
		try {
			State = 61;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case IDENTIFIER:
				EnterOuterAlt(_localctx, 1);
				{
				State = 57;
				Match(IDENTIFIER);
				State = 58;
				Match(Colon);
				State = 59;
				Match(IDENTIFIER);
				}
				break;
			case IRI:
				EnterOuterAlt(_localctx, 2);
				{
				State = 60;
				Match(IRI);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RuleBlockContext : ParserRuleContext {
		public IToken ruleType;
		public IToken ruleName;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OpenBrace() { return GetToken(RFEARParser.OpenBrace, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SwrlRuleContext swrlRule() {
			return GetRuleContext<SwrlRuleContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CloseBrace() { return GetToken(RFEARParser.CloseBrace, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(RFEARParser.SemiColon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(RFEARParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Observed() { return GetToken(RFEARParser.Observed, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Derived() { return GetToken(RFEARParser.Derived, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode With() { return GetToken(RFEARParser.With, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public DependsOnClauseBlockContext dependsOnClauseBlock() {
			return GetRuleContext<DependsOnClauseBlockContext>(0);
		}
		public RuleBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ruleBlock; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRuleBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RuleBlockContext ruleBlock() {
		RuleBlockContext _localctx = new RuleBlockContext(Context, State);
		EnterRule(_localctx, 4, RULE_ruleBlock);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 63;
			_localctx.ruleType = TokenStream.LT(1);
			_la = TokenStream.LA(1);
			if ( !(_la==Derived || _la==Observed) ) {
				_localctx.ruleType = ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 64;
			_localctx.ruleName = Match(IDENTIFIER);
			State = 66;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==With) {
				{
				State = 65;
				Match(With);
				}
			}

			State = 68;
			Match(OpenBrace);
			State = 69;
			swrlRule();
			State = 70;
			Match(CloseBrace);
			State = 72;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Depends_on) {
				{
				State = 71;
				dependsOnClauseBlock();
				}
			}

			State = 74;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SwrlRuleContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SwrlAntecedentContext swrlAntecedent() {
			return GetRuleContext<SwrlAntecedentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Indirection() { return GetToken(RFEARParser.Indirection, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SwrlConsequentContext swrlConsequent() {
			return GetRuleContext<SwrlConsequentContext>(0);
		}
		public SwrlRuleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_swrlRule; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSwrlRule(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SwrlRuleContext swrlRule() {
		SwrlRuleContext _localctx = new SwrlRuleContext(Context, State);
		EnterRule(_localctx, 6, RULE_swrlRule);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 76;
			swrlAntecedent();
			State = 77;
			Match(Indirection);
			State = 78;
			swrlConsequent();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SwrlAntecedentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AtomContext[] atom() {
			return GetRuleContexts<AtomContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public AtomContext atom(int i) {
			return GetRuleContext<AtomContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Conjunct() { return GetTokens(RFEARParser.Conjunct); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Conjunct(int i) {
			return GetToken(RFEARParser.Conjunct, i);
		}
		public SwrlAntecedentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_swrlAntecedent; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSwrlAntecedent(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SwrlAntecedentContext swrlAntecedent() {
		SwrlAntecedentContext _localctx = new SwrlAntecedentContext(Context, State);
		EnterRule(_localctx, 8, RULE_swrlAntecedent);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 80;
			atom();
			State = 85;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Conjunct) {
				{
				{
				State = 81;
				Match(Conjunct);
				State = 82;
				atom();
				}
				}
				State = 87;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SwrlConsequentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AtomContext[] atom() {
			return GetRuleContexts<AtomContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public AtomContext atom(int i) {
			return GetRuleContext<AtomContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Conjunct() { return GetTokens(RFEARParser.Conjunct); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Conjunct(int i) {
			return GetToken(RFEARParser.Conjunct, i);
		}
		public SwrlConsequentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_swrlConsequent; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSwrlConsequent(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SwrlConsequentContext swrlConsequent() {
		SwrlConsequentContext _localctx = new SwrlConsequentContext(Context, State);
		EnterRule(_localctx, 10, RULE_swrlConsequent);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 88;
			atom();
			State = 93;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Conjunct) {
				{
				{
				State = 89;
				Match(Conjunct);
				State = 90;
				atom();
				}
				}
				State = 95;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AtomContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ClassAtomContext classAtom() {
			return GetRuleContext<ClassAtomContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PropertyAtomContext propertyAtom() {
			return GetRuleContext<PropertyAtomContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BuiltinAtomContext builtinAtom() {
			return GetRuleContext<BuiltinAtomContext>(0);
		}
		public AtomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_atom; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAtom(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AtomContext atom() {
		AtomContext _localctx = new AtomContext(Context, State);
		EnterRule(_localctx, 12, RULE_atom);
		try {
			State = 99;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 96;
				classAtom();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 97;
				propertyAtom();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 98;
				builtinAtom();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ClassAtomContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IriContext iri() {
			return GetRuleContext<IriContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OpenParen() { return GetToken(RFEARParser.OpenParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public VariableContext variable() {
			return GetRuleContext<VariableContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CloseParen() { return GetToken(RFEARParser.CloseParen, 0); }
		public ClassAtomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_classAtom; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClassAtom(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ClassAtomContext classAtom() {
		ClassAtomContext _localctx = new ClassAtomContext(Context, State);
		EnterRule(_localctx, 14, RULE_classAtom);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 101;
			iri();
			State = 102;
			Match(OpenParen);
			State = 103;
			variable();
			State = 104;
			Match(CloseParen);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PropertyAtomContext : ParserRuleContext {
		public VariableContext subjectVariable;
		public ArgumentContext objectVariable;
		[System.Diagnostics.DebuggerNonUserCode] public IriContext iri() {
			return GetRuleContext<IriContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OpenParen() { return GetToken(RFEARParser.OpenParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma() { return GetToken(RFEARParser.Comma, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CloseParen() { return GetToken(RFEARParser.CloseParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public VariableContext variable() {
			return GetRuleContext<VariableContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentContext argument() {
			return GetRuleContext<ArgumentContext>(0);
		}
		public PropertyAtomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_propertyAtom; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPropertyAtom(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PropertyAtomContext propertyAtom() {
		PropertyAtomContext _localctx = new PropertyAtomContext(Context, State);
		EnterRule(_localctx, 16, RULE_propertyAtom);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 106;
			iri();
			State = 107;
			Match(OpenParen);
			State = 108;
			_localctx.subjectVariable = variable();
			State = 109;
			Match(Comma);
			State = 110;
			_localctx.objectVariable = argument();
			State = 111;
			Match(CloseParen);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BuiltinAtomContext : ParserRuleContext {
		public ArgumentContext arg1;
		public ArgumentContext arg2;
		[System.Diagnostics.DebuggerNonUserCode] public SwrlbIriContext swrlbIri() {
			return GetRuleContext<SwrlbIriContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OpenParen() { return GetToken(RFEARParser.OpenParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma() { return GetToken(RFEARParser.Comma, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CloseParen() { return GetToken(RFEARParser.CloseParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentContext[] argument() {
			return GetRuleContexts<ArgumentContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentContext argument(int i) {
			return GetRuleContext<ArgumentContext>(i);
		}
		public BuiltinAtomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_builtinAtom; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBuiltinAtom(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BuiltinAtomContext builtinAtom() {
		BuiltinAtomContext _localctx = new BuiltinAtomContext(Context, State);
		EnterRule(_localctx, 18, RULE_builtinAtom);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 113;
			swrlbIri();
			State = 114;
			Match(OpenParen);
			State = 115;
			_localctx.arg1 = argument();
			State = 116;
			Match(Comma);
			State = 117;
			_localctx.arg2 = argument();
			State = 118;
			Match(CloseParen);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public VariableContext variable() {
			return GetRuleContext<VariableContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LiteralContext literal() {
			return GetRuleContext<LiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IriContext iri() {
			return GetRuleContext<IriContext>(0);
		}
		public ArgumentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argument; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgument(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentContext argument() {
		ArgumentContext _localctx = new ArgumentContext(Context, State);
		EnterRule(_localctx, 20, RULE_argument);
		try {
			State = 123;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case VAR:
				EnterOuterAlt(_localctx, 1);
				{
				State = 120;
				variable();
				}
				break;
			case STRING_LITERAL:
			case NUMBER_LITERAL:
				EnterOuterAlt(_localctx, 2);
				{
				State = 121;
				literal();
				}
				break;
			case IRI:
			case IDENTIFIER:
				EnterOuterAlt(_localctx, 3);
				{
				State = 122;
				iri();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VAR() { return GetToken(RFEARParser.VAR, 0); }
		public VariableContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variable; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariable(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableContext variable() {
		VariableContext _localctx = new VariableContext(Context, State);
		EnterRule(_localctx, 22, RULE_variable);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 125;
			Match(VAR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LiteralContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL() { return GetToken(RFEARParser.STRING_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER_LITERAL() { return GetToken(RFEARParser.NUMBER_LITERAL, 0); }
		public LiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literal; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LiteralContext literal() {
		LiteralContext _localctx = new LiteralContext(Context, State);
		EnterRule(_localctx, 24, RULE_literal);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 127;
			_la = TokenStream.LA(1);
			if ( !(_la==STRING_LITERAL || _la==NUMBER_LITERAL) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IriContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public EntityUriContext entityUri() {
			return GetRuleContext<EntityUriContext>(0);
		}
		public IriContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_iri; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIri(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IriContext iri() {
		IriContext _localctx = new IriContext(Context, State);
		EnterRule(_localctx, 26, RULE_iri);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 129;
			entityUri();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SwrlbIriContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Swrlb() { return GetToken(RFEARParser.Swrlb, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Colon() { return GetToken(RFEARParser.Colon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(RFEARParser.IDENTIFIER, 0); }
		public SwrlbIriContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_swrlbIri; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSwrlbIri(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SwrlbIriContext swrlbIri() {
		SwrlbIriContext _localctx = new SwrlbIriContext(Context, State);
		EnterRule(_localctx, 28, RULE_swrlbIri);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 131;
			Match(Swrlb);
			State = 132;
			Match(Colon);
			State = 133;
			Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SwrlbOrIdentifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Swrlb() { return GetToken(RFEARParser.Swrlb, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(RFEARParser.IDENTIFIER, 0); }
		public SwrlbOrIdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_swrlbOrIdentifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSwrlbOrIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SwrlbOrIdentifierContext swrlbOrIdentifier() {
		SwrlbOrIdentifierContext _localctx = new SwrlbOrIdentifierContext(Context, State);
		EnterRule(_localctx, 30, RULE_swrlbOrIdentifier);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 135;
			_la = TokenStream.LA(1);
			if ( !(_la==Swrlb || _la==IDENTIFIER) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DependsOnClauseBlockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Depends_on() { return GetToken(RFEARParser.Depends_on, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public DependsOnClauseContext[] dependsOnClause() {
			return GetRuleContexts<DependsOnClauseContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public DependsOnClauseContext dependsOnClause(int i) {
			return GetRuleContext<DependsOnClauseContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comma() { return GetTokens(RFEARParser.Comma); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma(int i) {
			return GetToken(RFEARParser.Comma, i);
		}
		public DependsOnClauseBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dependsOnClauseBlock; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDependsOnClauseBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DependsOnClauseBlockContext dependsOnClauseBlock() {
		DependsOnClauseBlockContext _localctx = new DependsOnClauseBlockContext(Context, State);
		EnterRule(_localctx, 32, RULE_dependsOnClauseBlock);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 137;
			Match(Depends_on);
			State = 138;
			dependsOnClause();
			State = 143;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Comma) {
				{
				{
				State = 139;
				Match(Comma);
				State = 140;
				dependsOnClause();
				}
				}
				State = 145;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DependsOnClauseContext : ParserRuleContext {
		public IToken ruleName;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(RFEARParser.IDENTIFIER, 0); }
		public DependsOnClauseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dependsOnClause; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDependsOnClause(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DependsOnClauseContext dependsOnClause() {
		DependsOnClauseContext _localctx = new DependsOnClauseContext(Context, State);
		EnterRule(_localctx, 34, RULE_dependsOnClause);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 146;
			_localctx.ruleName = Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IncludeStatementContext : ParserRuleContext {
		public SwrlbOrIdentifierContext onto;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Include() { return GetToken(RFEARParser.Include, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(RFEARParser.SemiColon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SwrlbOrIdentifierContext[] swrlbOrIdentifier() {
			return GetRuleContexts<SwrlbOrIdentifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public SwrlbOrIdentifierContext swrlbOrIdentifier(int i) {
			return GetRuleContext<SwrlbOrIdentifierContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comma() { return GetTokens(RFEARParser.Comma); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma(int i) {
			return GetToken(RFEARParser.Comma, i);
		}
		public IncludeStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_includeStatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIncludeStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IncludeStatementContext includeStatement() {
		IncludeStatementContext _localctx = new IncludeStatementContext(Context, State);
		EnterRule(_localctx, 36, RULE_includeStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 148;
			Match(Include);
			State = 149;
			_localctx.onto = swrlbOrIdentifier();
			State = 154;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Comma) {
				{
				{
				State = 150;
				Match(Comma);
				State = 151;
				_localctx.onto = swrlbOrIdentifier();
				}
				}
				State = 156;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 157;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrefixStatementContext : ParserRuleContext {
		public IToken prefixLabel;
		public IToken prefixUri;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Prefix_() { return GetToken(RFEARParser.Prefix_, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OpenParen() { return GetToken(RFEARParser.OpenParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma() { return GetToken(RFEARParser.Comma, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CloseParen() { return GetToken(RFEARParser.CloseParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(RFEARParser.SemiColon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STRING_LITERAL() { return GetTokens(RFEARParser.STRING_LITERAL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL(int i) {
			return GetToken(RFEARParser.STRING_LITERAL, i);
		}
		public PrefixStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prefixStatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrefixStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrefixStatementContext prefixStatement() {
		PrefixStatementContext _localctx = new PrefixStatementContext(Context, State);
		EnterRule(_localctx, 38, RULE_prefixStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 159;
			Match(Prefix_);
			State = 160;
			Match(OpenParen);
			State = 161;
			_localctx.prefixLabel = Match(STRING_LITERAL);
			State = 162;
			Match(Comma);
			State = 163;
			_localctx.prefixUri = Match(STRING_LITERAL);
			State = 164;
			Match(CloseParen);
			State = 165;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RulesetDefinitionBlockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RulesetDefinitionStatementContext rulesetDefinitionStatement() {
			return GetRuleContext<RulesetDefinitionStatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OntologyStatementContext[] ontologyStatement() {
			return GetRuleContexts<OntologyStatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public OntologyStatementContext ontologyStatement(int i) {
			return GetRuleContext<OntologyStatementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IncludeStatementContext includeStatement() {
			return GetRuleContext<IncludeStatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PrefixStatementContext[] prefixStatement() {
			return GetRuleContexts<PrefixStatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PrefixStatementContext prefixStatement(int i) {
			return GetRuleContext<PrefixStatementContext>(i);
		}
		public RulesetDefinitionBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rulesetDefinitionBlock; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRulesetDefinitionBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RulesetDefinitionBlockContext rulesetDefinitionBlock() {
		RulesetDefinitionBlockContext _localctx = new RulesetDefinitionBlockContext(Context, State);
		EnterRule(_localctx, 40, RULE_rulesetDefinitionBlock);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 167;
			rulesetDefinitionStatement();
			State = 169;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 168;
				ontologyStatement();
				}
				}
				State = 171;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==Ontology );
			State = 174;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Include) {
				{
				State = 173;
				includeStatement();
				}
			}

			State = 179;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Prefix_) {
				{
				{
				State = 176;
				prefixStatement();
				}
				}
				State = 181;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RulesetDefinitionStatementContext : ParserRuleContext {
		public IToken rulsetName;
		public IToken rulesetCategory;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Define() { return GetToken(RFEARParser.Define, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ruleset() { return GetToken(RFEARParser.Ruleset, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OpenParen() { return GetToken(RFEARParser.OpenParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma() { return GetToken(RFEARParser.Comma, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CloseParen() { return GetToken(RFEARParser.CloseParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(RFEARParser.SemiColon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STRING_LITERAL() { return GetTokens(RFEARParser.STRING_LITERAL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL(int i) {
			return GetToken(RFEARParser.STRING_LITERAL, i);
		}
		public RulesetDefinitionStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rulesetDefinitionStatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRulesetDefinitionStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RulesetDefinitionStatementContext rulesetDefinitionStatement() {
		RulesetDefinitionStatementContext _localctx = new RulesetDefinitionStatementContext(Context, State);
		EnterRule(_localctx, 42, RULE_rulesetDefinitionStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 182;
			Match(Define);
			State = 183;
			Match(Ruleset);
			State = 184;
			Match(OpenParen);
			State = 185;
			_localctx.rulsetName = Match(STRING_LITERAL);
			State = 186;
			Match(Comma);
			State = 187;
			_localctx.rulesetCategory = Match(STRING_LITERAL);
			State = 188;
			Match(CloseParen);
			State = 189;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OntologyStatementContext : ParserRuleContext {
		public IToken ontUrl;
		public IToken ontPrefix;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ontology() { return GetToken(RFEARParser.Ontology, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OpenParen() { return GetToken(RFEARParser.OpenParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comma() { return GetTokens(RFEARParser.Comma); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma(int i) {
			return GetToken(RFEARParser.Comma, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CloseParen() { return GetToken(RFEARParser.CloseParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SemiColon() { return GetToken(RFEARParser.SemiColon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STRING_LITERAL() { return GetTokens(RFEARParser.STRING_LITERAL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL(int i) {
			return GetToken(RFEARParser.STRING_LITERAL, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OntologyPrefixStatementContext[] ontologyPrefixStatement() {
			return GetRuleContexts<OntologyPrefixStatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public OntologyPrefixStatementContext ontologyPrefixStatement(int i) {
			return GetRuleContext<OntologyPrefixStatementContext>(i);
		}
		public OntologyStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ontologyStatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOntologyStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OntologyStatementContext ontologyStatement() {
		OntologyStatementContext _localctx = new OntologyStatementContext(Context, State);
		EnterRule(_localctx, 44, RULE_ontologyStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 191;
			Match(Ontology);
			State = 192;
			Match(OpenParen);
			State = 193;
			_localctx.ontUrl = Match(STRING_LITERAL);
			State = 194;
			Match(Comma);
			State = 195;
			_localctx.ontPrefix = Match(STRING_LITERAL);
			State = 200;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Comma) {
				{
				{
				State = 196;
				Match(Comma);
				State = 197;
				ontologyPrefixStatement();
				}
				}
				State = 202;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 203;
			Match(CloseParen);
			State = 204;
			Match(SemiColon);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OntologyPrefixStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(RFEARParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Colon() { return GetToken(RFEARParser.Colon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL() { return GetToken(RFEARParser.STRING_LITERAL, 0); }
		public OntologyPrefixStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ontologyPrefixStatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRFEARParserVisitor<TResult> typedVisitor = visitor as IRFEARParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOntologyPrefixStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OntologyPrefixStatementContext ontologyPrefixStatement() {
		OntologyPrefixStatementContext _localctx = new OntologyPrefixStatementContext(Context, State);
		EnterRule(_localctx, 46, RULE_ontologyPrefixStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 206;
			Match(IDENTIFIER);
			State = 207;
			Match(Colon);
			State = 208;
			Match(STRING_LITERAL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,31,211,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,1,0,1,0,5,0,51,8,0,10,0,12,0,54,9,0,1,0,1,0,1,1,1,
		1,1,1,1,1,3,1,62,8,1,1,2,1,2,1,2,3,2,67,8,2,1,2,1,2,1,2,1,2,3,2,73,8,2,
		1,2,1,2,1,3,1,3,1,3,1,3,1,4,1,4,1,4,5,4,84,8,4,10,4,12,4,87,9,4,1,5,1,
		5,1,5,5,5,92,8,5,10,5,12,5,95,9,5,1,6,1,6,1,6,3,6,100,8,6,1,7,1,7,1,7,
		1,7,1,7,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,10,1,
		10,1,10,3,10,124,8,10,1,11,1,11,1,12,1,12,1,13,1,13,1,14,1,14,1,14,1,14,
		1,15,1,15,1,16,1,16,1,16,1,16,5,16,142,8,16,10,16,12,16,145,9,16,1,17,
		1,17,1,18,1,18,1,18,1,18,5,18,153,8,18,10,18,12,18,156,9,18,1,18,1,18,
		1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,20,1,20,4,20,170,8,20,11,20,
		12,20,171,1,20,3,20,175,8,20,1,20,5,20,178,8,20,10,20,12,20,181,9,20,1,
		21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,22,1,22,1,22,1,22,1,22,1,
		22,1,22,5,22,199,8,22,10,22,12,22,202,9,22,1,22,1,22,1,22,1,23,1,23,1,
		23,1,23,1,23,0,0,24,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,
		38,40,42,44,46,0,3,1,0,5,6,1,0,29,30,2,0,1,1,31,31,202,0,48,1,0,0,0,2,
		61,1,0,0,0,4,63,1,0,0,0,6,76,1,0,0,0,8,80,1,0,0,0,10,88,1,0,0,0,12,99,
		1,0,0,0,14,101,1,0,0,0,16,106,1,0,0,0,18,113,1,0,0,0,20,123,1,0,0,0,22,
		125,1,0,0,0,24,127,1,0,0,0,26,129,1,0,0,0,28,131,1,0,0,0,30,135,1,0,0,
		0,32,137,1,0,0,0,34,146,1,0,0,0,36,148,1,0,0,0,38,159,1,0,0,0,40,167,1,
		0,0,0,42,182,1,0,0,0,44,191,1,0,0,0,46,206,1,0,0,0,48,52,3,40,20,0,49,
		51,3,4,2,0,50,49,1,0,0,0,51,54,1,0,0,0,52,50,1,0,0,0,52,53,1,0,0,0,53,
		55,1,0,0,0,54,52,1,0,0,0,55,56,5,0,0,1,56,1,1,0,0,0,57,58,5,31,0,0,58,
		59,5,18,0,0,59,62,5,31,0,0,60,62,5,27,0,0,61,57,1,0,0,0,61,60,1,0,0,0,
		62,3,1,0,0,0,63,64,7,0,0,0,64,66,5,31,0,0,65,67,5,11,0,0,66,65,1,0,0,0,
		66,67,1,0,0,0,67,68,1,0,0,0,68,69,5,14,0,0,69,70,3,6,3,0,70,72,5,15,0,
		0,71,73,3,32,16,0,72,71,1,0,0,0,72,73,1,0,0,0,73,74,1,0,0,0,74,75,5,16,
		0,0,75,5,1,0,0,0,76,77,3,8,4,0,77,78,5,20,0,0,78,79,3,10,5,0,79,7,1,0,
		0,0,80,85,3,12,6,0,81,82,5,19,0,0,82,84,3,12,6,0,83,81,1,0,0,0,84,87,1,
		0,0,0,85,83,1,0,0,0,85,86,1,0,0,0,86,9,1,0,0,0,87,85,1,0,0,0,88,93,3,12,
		6,0,89,90,5,19,0,0,90,92,3,12,6,0,91,89,1,0,0,0,92,95,1,0,0,0,93,91,1,
		0,0,0,93,94,1,0,0,0,94,11,1,0,0,0,95,93,1,0,0,0,96,100,3,14,7,0,97,100,
		3,16,8,0,98,100,3,18,9,0,99,96,1,0,0,0,99,97,1,0,0,0,99,98,1,0,0,0,100,
		13,1,0,0,0,101,102,3,26,13,0,102,103,5,12,0,0,103,104,3,22,11,0,104,105,
		5,13,0,0,105,15,1,0,0,0,106,107,3,26,13,0,107,108,5,12,0,0,108,109,3,22,
		11,0,109,110,5,17,0,0,110,111,3,20,10,0,111,112,5,13,0,0,112,17,1,0,0,
		0,113,114,3,28,14,0,114,115,5,12,0,0,115,116,3,20,10,0,116,117,5,17,0,
		0,117,118,3,20,10,0,118,119,5,13,0,0,119,19,1,0,0,0,120,124,3,22,11,0,
		121,124,3,24,12,0,122,124,3,26,13,0,123,120,1,0,0,0,123,121,1,0,0,0,123,
		122,1,0,0,0,124,21,1,0,0,0,125,126,5,28,0,0,126,23,1,0,0,0,127,128,7,1,
		0,0,128,25,1,0,0,0,129,130,3,2,1,0,130,27,1,0,0,0,131,132,5,1,0,0,132,
		133,5,18,0,0,133,134,5,31,0,0,134,29,1,0,0,0,135,136,7,2,0,0,136,31,1,
		0,0,0,137,138,5,10,0,0,138,143,3,34,17,0,139,140,5,17,0,0,140,142,3,34,
		17,0,141,139,1,0,0,0,142,145,1,0,0,0,143,141,1,0,0,0,143,144,1,0,0,0,144,
		33,1,0,0,0,145,143,1,0,0,0,146,147,5,31,0,0,147,35,1,0,0,0,148,149,5,8,
		0,0,149,154,3,30,15,0,150,151,5,17,0,0,151,153,3,30,15,0,152,150,1,0,0,
		0,153,156,1,0,0,0,154,152,1,0,0,0,154,155,1,0,0,0,155,157,1,0,0,0,156,
		154,1,0,0,0,157,158,5,16,0,0,158,37,1,0,0,0,159,160,5,9,0,0,160,161,5,
		12,0,0,161,162,5,29,0,0,162,163,5,17,0,0,163,164,5,29,0,0,164,165,5,13,
		0,0,165,166,5,16,0,0,166,39,1,0,0,0,167,169,3,42,21,0,168,170,3,44,22,
		0,169,168,1,0,0,0,170,171,1,0,0,0,171,169,1,0,0,0,171,172,1,0,0,0,172,
		174,1,0,0,0,173,175,3,36,18,0,174,173,1,0,0,0,174,175,1,0,0,0,175,179,
		1,0,0,0,176,178,3,38,19,0,177,176,1,0,0,0,178,181,1,0,0,0,179,177,1,0,
		0,0,179,180,1,0,0,0,180,41,1,0,0,0,181,179,1,0,0,0,182,183,5,3,0,0,183,
		184,5,4,0,0,184,185,5,12,0,0,185,186,5,29,0,0,186,187,5,17,0,0,187,188,
		5,29,0,0,188,189,5,13,0,0,189,190,5,16,0,0,190,43,1,0,0,0,191,192,5,7,
		0,0,192,193,5,12,0,0,193,194,5,29,0,0,194,195,5,17,0,0,195,200,5,29,0,
		0,196,197,5,17,0,0,197,199,3,46,23,0,198,196,1,0,0,0,199,202,1,0,0,0,200,
		198,1,0,0,0,200,201,1,0,0,0,201,203,1,0,0,0,202,200,1,0,0,0,203,204,5,
		13,0,0,204,205,5,16,0,0,205,45,1,0,0,0,206,207,5,31,0,0,207,208,5,18,0,
		0,208,209,5,29,0,0,209,47,1,0,0,0,14,52,61,66,72,85,93,99,123,143,154,
		171,174,179,200
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace FEAR
