<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CsvHelper" Version="33.1.0" />
		<PackageReference Include="dotNetRdf" Version="3.4.0" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="Neo4j.Driver" Version="5.28.3" />
		<PackageReference Include="OpenAI" Version="2.5.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FEAR.Lang\FEAR.Lang.csproj" />
		<ProjectReference Include="..\FEAR.Domain\FEAR.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="SAM">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Update="SAM-Domain-User.ifear">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Update="SAM-File.cfear">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Update="SAM-File.gfear">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Update="SAM-Domain-MID.ifear">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
