// <auto-generated />
using System;
using FEAR.Host.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FEAR.Hosted.Migrations.InvestigationManagementDb
{
    [DbContext(typeof(InvestigationManagementDbContext))]
    partial class InvestigationManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("FEAR.Domain.Dto.ColorMap.ColorMapSet", b =>
                {
                    b.Property<Guid>("ColorMapSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorMaps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityDiscriminator")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ColorMapSetId");

                    b.ToTable("ColorMapSets", (string)null);
                });

            modelBuilder.Entity("FEAR.Domain.Dto.InvestigationStore.InvestigationConfiguration", b =>
                {
                    b.Property<Guid>("InvestigationConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HostedUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvestigationId")
                        .HasColumnType("uuid");

                    b.HasKey("InvestigationConfigurationId");

                    b.ToTable("InvestigationConfigurations", (string)null);
                });

            modelBuilder.Entity("FEAR.Domain.Dto.InvestigationStore.InvestigationInfo", b =>
                {
                    b.Property<Guid>("InvestigationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CaseDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("timestamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamespaceAbbrev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InvestigationId");

                    b.ToTable("Investigations", (string)null);
                });

            modelBuilder.Entity("FEAR.Domain.Dto.InvestigationStore.InvestigationQuery", b =>
                {
                    b.Property<Guid>("InvestigationQueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvestigationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("timestamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InvestigationQueryId");

                    b.ToTable("InvestigationQueries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
