using static FEAR.RFEARParser;

namespace FEAR.RFEAR
{
    /// <summary>
    /// Represents a FEAR graph codifier generated by parsing an input.
    /// </summary>
    public class FEARRuleSet
    {
        /// <summary>
        /// The root of a FEAR graph codifier concrete syntax tree generated by the parser.
        /// </summary>
        public ProgramContext RFEARCtxRoot { get; private set; }

        /// <summary>
        /// The collection of all parse errors that may have been encountered during parsing.
        /// </summary>
        public ICollection<FEARErrorBase> ParseErrors { get; private set; }
        /// <summary>
        /// Returns true if parse errors were encountered, false otherwise.
        /// </summary>
        public bool HasParseErrors
        {
            get { return ParseErrors.Count != 0; }
        }

        public string SourceFileName { get; set; }

        /// <summary>
        /// Initialises a new instance of a FEARProgram with the given root context and collection of parse errors.
        /// </summary>
        /// <param name="FEARCstRoot">The root context of the concrete syntax tree generated by the parser.</param>
        /// <param name="parseErrors">The collection of parse errors encountered during parsing.</param>
        public FEARRuleSet(ProgramContext RFEARCstRoot, ICollection<FEARErrorBase> parseErrors, string filename)
        {
            RFEARCtxRoot = RFEARCstRoot;
            ParseErrors = parseErrors;
            SourceFileName = filename;
        }
    }
}
