using static FEAR.CFEARParser;

namespace FEAR.CFEAR
{
    /// <summary>
    /// Represents a FEAR collector generated by parsing an input.
    /// Encapsulates the root of the parsed collector syntax tree and any parse errors encountered.
    /// Used as the main data structure for compilation of a FEAR collector program.
    /// </summary>
    public class FEARCollector
    {
        /// <summary>
        /// The root of a FEAR collector concrete syntax tree generated by the parser.
        /// This context provides access to all top-level statements and blocks in the parsed collector program.
        /// </summary>
        public ProgramContext CFEARCtxRoot { get; private set; }

        /// <summary>
        /// The collection of all parse errors that may have been encountered during parsing.
        /// Each error provides details such as the symbol, line, column, and error message.
        /// </summary>
        public ICollection<FEARErrorBase> ParseErrors { get; private set; }

        /// <summary>
        /// Returns true if parse errors were encountered, false otherwise.
        /// </summary>
        public bool HasParseErrors
        {
            get { return ParseErrors.Count != 0; }
        }

        /// <summary>
        /// Initializes a new instance of a FEARCollector with the given root context and collection of parse errors.
        /// </summary>
        /// <param name="CFEARCstRoot">The root context of the concrete syntax tree generated by the parser.</param>
        /// <param name="parseErrors">The collection of parse errors encountered during parsing.</param>
        public FEARCollector(ProgramContext CFEARCstRoot, ICollection<FEARErrorBase> parseErrors)
        {
            CFEARCtxRoot = CFEARCstRoot;
            ParseErrors = parseErrors;
        }
    }
}
