// <auto-generated />
using System;
using FEAR.Host.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FEAR.Hosted.Migrations.HostedSystemDb
{
    [DbContext(typeof(HostedSystemDbContext))]
    partial class HostedSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("FEAR.Host.Domain.Database.Model.SystemWideProperty", b =>
                {
                    b.Property<Guid>("SystemWidePropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SystemWidePropertyId");

                    b.ToTable("SystemWideProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
