namespace FEAR.Domain.Agents
{
    /// <summary>
    /// Represents a single message contribution from an agent in the interaction.
    /// Supports tracking multiple agent contributions within a single interaction.
    /// </summary>
    public class AgentMessage
    {
        /// <summary>
        /// The unique identifier of the agent that generated this message.
        /// </summary>
        public string AgentId { get; set; } = string.Empty;

        /// <summary>
        /// The name of the agent (for display purposes).
        /// </summary>
        public string AgentName { get; set; } = string.Empty;

        /// <summary>
        /// The content of the message generated by the agent.
        /// </summary>
        public string Content { get; set; } = string.Empty;

        /// <summary>
        /// The timestamp when this message was generated.
        /// </summary>
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Optional metadata about the agent execution (e.g., execution time, token count, etc.).
        /// </summary>
        public Dictionary<string, object> Metadata { get; set; } = new Dictionary<string, object>();
    }
}
