using static FEAR.IFEARParser;

namespace FEAR.IFEAR
{
    /// <summary>
    /// Represents a FEAR interpreter generated by parsing an input.
    /// </summary>
    public class FEARInterpreter
    {
        /// <summary>
        /// The root of a FEAR interpreter concrete syntax tree generated by the parser.
        /// </summary>
        public ProgramContext IFEARCtxRoot { get; private set; }

        /// <summary>
        /// The collection of all parse errors that may have been encountered during parsing.
        /// </summary>
        public ICollection<FEARErrorBase> ParseErrors { get; private set; }
        /// <summary>
        /// Returns true if parse errors were encountered, false otherwise.
        /// </summary>
        public bool HasParseErrors
        {
            get { return ParseErrors.Count != 0; }
        }

        /// <summary>
        /// Initialises a new instance of a FEARProgram with the given root context and collection of parse errors.
        /// </summary>
        /// <param name="FEARCstRoot">The root context of the concrete syntax tree generated by the parser.</param>
        /// <param name="parseErrors">The collection of parse errors encountered during parsing.</param>
        public FEARInterpreter(ProgramContext IFEARCstRoot, ICollection<FEARErrorBase> parseErrors)
        {
            IFEARCtxRoot = IFEARCstRoot;
            ParseErrors = parseErrors;
        }
    }
}
