<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.3.0" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.20">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel.Core" Version="2.3.9" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.20" />
	  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
	  <PackageReference Include="OpenIddict.Abstractions" Version="7.1.0" />
	  <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="7.1.0" />
	  <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.20" />
	  <PackageReference Include="System.Runtime.Caching" Version="8.0.1" />
	  <PackageReference Include="Jitbit.FastCache" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FEAR.Domain\FEAR.Domain.csproj" />
    <ProjectReference Include="..\FEAR.Host.Domain\FEAR.Host.Domain.csproj" />
    <ProjectReference Include="..\FEAR.Runtime\FEAR.Runtime.csproj" />
  </ItemGroup>

</Project>
