<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<StaticWebAssetBasePath>administration</StaticWebAssetBasePath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.20" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.20" PrivateAssets="all" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="8.0.20" />
		<PackageReference Include="OpenIddict.EntityFrameworkCore" Version="7.1.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\FEAR.Blazor.Shared\FEAR.Blazor.Shared.csproj" />
	  <ProjectReference Include="..\FEAR.Host.Domain\FEAR.Host.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Content Update="libman.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		  <CopyToPublishDirectory>Never</CopyToPublishDirectory>
	  </Content>
	  <Content Update="wwwroot\Test.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

</Project>
