<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="compilerconfig.json" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Components\Omnibar\Omnibar.razor.scss" />
	</ItemGroup>

	<ItemGroup>
		<None Include="compilerconfig.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="EventAggregator.Blazor" Version="2.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.20" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="8.0.20" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.20" PrivateAssets="all" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />

		<PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.9.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FEAR.Blazor.Shared\FEAR.Blazor.Shared.csproj" />
		<ProjectReference Include="..\FEAR.Host.Domain\FEAR.Host.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\lib\graphology\" />
	</ItemGroup>

	<ItemGroup>
	  <Content Update="libman.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		  <CopyToPublishDirectory>Never</CopyToPublishDirectory>
	  </Content>
	</ItemGroup>

	<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
		<Exec Command="npm install" WorkingDirectory="npm_packages" />
		<Exec Command="npm run build" WorkingDirectory="npm_packages" />
	</Target>
</Project>
